service: my-express-service

frameworkVersion: '3'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_REGION, 'ap-south-1'}
  runtime: nodejs20.x
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221

functions:
  api:
    handler: handler.lambdaHandler
    events:
      - httpApi:            # uses API Gateway HTTP API (v2). For REST API v1 use 'http'
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline   # optional for local dev

package:
  exclude:
    - node_modules/**
    - .git/**
